variables:
    PROJECT_NAME: "Pardik-PBM-Resident-Panel"  
    IMAGE_NAME: "pardik.pbm.resident.panel"
    CI_REGISTRY_REPO: "reg.pardikiot.com"
stages: 
  - build
  - deploy

build-push:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker build -t $CI_REGISTRY_REPO/$IMAGE_NAME:$CI_PIPELINE_ID . 
    - docker push $CI_REGISTRY_REPO/$IMAGE_NAME:$CI_PIPELINE_ID
  only:
    - develop

deploy:
  stage: deploy
  script:
  - echo "APPEL de CURL"
  - curl https://sshengine.pardikiot.com/SSH/Deploy/$PROJECT_NAME/%20$CI_REGISTRY_REPO%2F$IMAGE_NAME%3A$CI_PIPELINE_ID
  - echo "content"
  - exit 0
  only:
    - develop
